### PR TITLE
Home page merge request

### PR DESCRIPTION
**Pull request by Mikearaya**
## features included on the current pull request
- mobile-first responsive design to support screen sizes from 300px - 767px
- tablet view support to support screen sizes from 768px - 1023px;
- Desktop support to support screen sizes from 1024px and above

### All the responsivity is achieved using plain CSS media queries

# looking forward to your review. :smile:

### CODE REVIEW

**Comment by sumancrest0001** [comment]
Hello TEAM,
It looks like you forgot to add the linter configuration for the project. There is no .stickler.yml file.
Please check and add the file and submit for another review.

Please reach out to me on slack **Suman Shrestha**.

Happy coding  :slightly_smiling_face:

**Comment by Mikearaya** [comment]
sorry about that, we must have forgotten it.... on it.

**Comment by sumancrest0001** [comment]
**Status: changes required**
**Magnificent job TEAM,**  :clap: :clap: 
It looks just perfect and I have to admit it.
[Required] Everything looks great and ticked all the requirements but it seems you forgot to implement one requirement. We have to add **TNW** text on the main article and which should be visible only on the large screen. Please have a look
In your project. :point_down:  :point_down: 
Screenshot from 2020-04-11 17-10-28

It should be :point_down: :point_down: 
Screenshot from 2020-04-11 17-10-40

**Comment by sumancrest0001** [comment]
[Optional] Can you please add a gradient look on the main article? It will be an icing on the cake.

**Comment by sumancrest0001** [comment]
[Optional] it looks good if we add some margin between two sections so that it looks like the original one. Please have a look
currently :point_down: 
Screenshot from 2020-04-11 16-59-50

In the original project :point_down: 
Screenshot from 2020-04-11 16-59-57

**Comment by sumancrest0001** [comment]
Optional changes are not mandatory to get a green signal from our side. Please make the requested changes and submit the project for another review.

Feel free to contact me on Slack **Suman Shrestha**
**Happy coding**

**Comment by Mikearaya** [comment]
thank you @sumancrest0001 for your quick and helpful response. we will start working on the requirements you mentioned.
one confusion is there is a gradient already so I don't know what you mean about that.
Thank you again.

**Comment by sumancrest0001** [comment]
**STATUS: APPROVED** 
**Congratulation TEAM.**
It's a  **YES** from my side and now you can merge the branch to the master.
Sorry for the mistake. 
Anyway, best of for the next project.
mission

**Pull request merged**
